### ISSUE TITLE
Fetching calendars fails due to datetime bug

### ISSUE THREAD

**Issue by ghost** [mandarons/icloudpy#26]
Call api.calendar.events() fails with:
```
Traceback (most recent call last):
  File "/home/i/test.py", line 42, in <module>
    my_events = api.calendar.events()
  File "/home/i/.local/lib/python3.10/site-packages/icloudpy/services/calendar.py", line 71, in events
    self.refresh_client(from_dt, to_dt)
  File "/home/i/.local/lib/python3.10/site-packages/icloudpy/services/calendar.py", line 51, in refresh_client
    from_dt = datetime(today.year, today.month, first_day)
ValueError: day is out of range for month
```
Identical issue to [](https://github.com/picklepete/pyicloud/issues/389) so I assume it's the same pre-existing issue copied from pyicloud to icloudpy.

**Comment by mandarons** [comment]
Can you share steps to reproduce?
