### ISSUE TITLE
Will accounts without 2FA authentication still be supported? The account in this link does not have 2FA enabled: https://d3k4b.sha.cx/19a6e7e2ab17d7b8add049698a802ef5.

### ISSUE THREAD

**Issue by 14278358** [mandarons/icloudpy#46]
Will accounts without 2FA authentication still be supported? The account in this link does not have 2FA enabled: https://d3k4b.sha.cx/19a6e7e2ab17d7b8add049698a802ef5.

Traceback (most recent call last):
File "starters\icloudpd.py", line 6, in
File "click\core.py", line 1157, in call
File "click\core.py", line 1078, in main
File "click\core.py", line 1434, in invoke
File "click\core.py", line 783, in invoke
File "icloudpd\base.py", line 745, in main
File "icloudpd\base.py", line 1179, in core
File "icloudpd\authentication.py", line 53, in authenticate_
File "pyicloud_ipd\base.py", line 157, in init
File "pyicloud_ipd\base.py", line 221, in authenticate
File "pyicloud_ipd\base.py", line 247, in _authenticate_with_token
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Missing apple_id field (Missing apple_id field)'))
[5832] Failed to execute script 'icloudpd' due to unhandled exception!

**Comment by mandarons** [comment]
No. Account without 2FA won't be supported by this library.
